name: PostgreSQL via brew-on-linux
on: [push]
jobs:
  pg16-via-brew:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Linuxbrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

          echo >> /home/runner/.bashrc
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Install postgresql@16
        run: brew install postgresql@16

      - name: Check pg_dump version
        run: pg_dump --version
